# Generated by Django 3.2.5 on 2021-09-13 02:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='grouptags',
            name='name',
        ),
        migrations.AddField(
            model_name='grouptags',
            name='create_user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to='app.users'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignments',
            name='is_finished',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='notifying_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='assignments',
            name='required_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='grouptags',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grouptag_user', to='app.users'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='collaborating_group_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.grouptags'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='collaborating_member_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collaborating_member', to='app.users'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='is_all_day',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='notifying_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_user', to='app.users'),
        ),
        migrations.AlterField(
            model_name='todolists',
            name='subjects_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.subjects'),
        ),
        migrations.AddField(
            model_name='grouptags',
            name='groupname_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='app.groupnames'),
            preserve_default=False,
        ),
    ]
