# Generated by Django 3.2.5 on 2021-09-13 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210913_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupnames',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupnames',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
