# Generated by Django 3.2.5 on 2021-09-14 02:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210913_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='end_time',
        ),
        migrations.AddField(
            model_name='assignments',
            name='margin',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignments',
            name='to_do_list_id',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='app.todolists'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todolists',
            name='notifying_time',
            field=models.TimeField(null=True),
        ),
    ]
